#!/bin/sh

set -eu

# Format staged files
if ! cargo fmt -- --check; then
  echo "There are some code style issues."
  echo "Run cargo fmt first."
  exit 1
fi

# Lint staged files
if ! cargo clippy --all-targets -- -D warnings; then
  echo "There are some clippy issues."
  exit 1
fi

# Full test
if ! cargo test; then
  echo "There are some test issues."
  exit 1
fi

exit 0
